[package]
name = "bip39"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.79.0"

[dependencies]
flutter_rust_bridge = "1.79.0"
bip39 = { version = "2.0.0", features = ["spanish", "rand"] }
hex = "0.4.3"
