name: unified_mnemonic
description: >
  A Dart library to generate and restore mnemonics and derive other keys and seeds from them.
  This makes it possible to have a unified wallet, which means having just one mnemonic for different wallets. 
  For example, have a Bitcoin on-chain wallet, a Bitcoin on-chain wallet with passphrase and a Lightning node wallet, 
  all derived from one 'unified' mnemonic.
version: 0.0.1
homepage: https://kumuly.dev
repository: https://github.com/kumuly/fluttoshi_packages
issue_tracker: https://github.com/kumuly/fluttoshi_packages/issues

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  ffi: ^2.0.2
  flutter_rust_bridge: ^1.79.0
  # path: ^1.8.0

dev_dependencies:
  ffigen: ^8.0.2
  lints: ^2.0.0
  test: ^1.21.0
