name: fluttoshi_packages
repository: https://github.com/kumuly/fluttoshi_packages

packages:
  - packages/*

scripts:
  analyze:
    exec: flutter analyze .
    description: Analyze a specific package in this project.

  check-format:
    exec: dart format --set-exit-if-changed .
    description: Check the format of a specific package in this project.

  format:
    exec: dart format .
    description: Format a specific package in this project.

  version:
    description: Updates version numbers in all build files
    run: bash scripts/version.sh

  build:
    run: melos run build:apple && melos run build:android && melos run build:other
    description: Build all native libraries for the project.

  build:apple:
    run: bash scripts/build-apple.sh
    description: Build the XCFramework for iOS and macOS.

  build:android:
    run: bash scripts/build-android.sh
    description: Build the .tar.gz for Android.

  build:other:
    run: bash scripts/build-other.sh
    description: Build the .tar.gz for all other platforms.

  copy:
    run: melos run copy:apple && melos run copy:android && melos run copy:other
    description: Copy all native libraries to the platform specific folders of the Flutter projects.

  copy:apple:
    run: bash scripts/copy-apple.sh
    description: Copy the XCFramework's to the ios and macos folders of the Flutter projects.

  copy:android:
    run: bash scripts/copy-android.sh
    description: Copy the .tar.gz's to the android folder of the Flutter projects.

  copy:other:
    run: bash scripts/copy-other.sh
    description: Copy the .tar.gz's to the linux and windows folder of the Flutter projects.

  test:
    run: melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this project.

  test:dart:
    run: melos exec -c 1 --fail-fast -- "dart test test"
    description: Run Dart tests for a specific package in this project.
    packageFilters:
      flutter: false
      dirExists: test

  test:flutter:
    run: melos exec -c 1 --fail-fast -- "flutter test test"
    description: Run Flutter tests for a specific package in this project.
    packageFilters:
      flutter: true
      dirExists: test
