[package]
name = "unified_mnemonic"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.62.1"

[dependencies]
flutter_rust_bridge = "1.62.1"
bdk = { version = "0.28.0", default-features = true, features = ["keys-bip39"] }
bip39 = { version = "2.0.0", features = ["spanish", "rand"] }
hex = "0.4.3"