[package]
name = "lightning-message-ffi"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = 'lightning_message_ffi'
crate-type = ['cdylib', 'staticlib']

[dependencies]


[build-dependencies]
cbindgen = "0.24.3"