[package]
name = "lightning_message"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.79.0"

[dependencies]
flutter_rust_bridge = "1.79.0"
lightning = "0.0.116"
bitcoin = "0.29.0"
hex = "0.4.3"
