// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.80.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'bridge_generated.dart';
export 'bridge_generated.dart';

class LightningMessagePlatform extends FlutterRustBridgeBase<LightningMessageWire> with FlutterRustBridgeSetupMixin {
  LightningMessagePlatform(FutureOr<WasmModule> dylib) : super(LightningMessageWire(dylib)) {
    setupMixinConstructor();
  }
  Future<void> setup() => inner.init;

// Section: api2wire

  @protected
  String api2wire_String(String raw) {
    return raw;
  }

  @protected
  List<dynamic> api2wire_box_autoadd_signer(Signer raw) {
    return api2wire_signer(raw);
  }

  @protected
  List<dynamic> api2wire_signer(Signer raw) {
    return [
      api2wire_u8_array_32(raw.secretKeyBytes),
      api2wire_String(raw.nodeId)
    ];
  }

  @protected
  Uint8List api2wire_u8_array_32(U8Array32 raw) {
    return Uint8List.fromList(raw);
  }

  @protected
  Uint8List api2wire_u8_array_64(U8Array64 raw) {
    return Uint8List.fromList(raw);
  }

  @protected
  Uint8List api2wire_uint_8_list(Uint8List raw) {
    return raw;
  }
// Section: finalizer
}

// Section: WASM wire module

@JS('wasm_bindgen')
external LightningMessageWasmModule get wasmModule;

@JS()
@anonymous
class LightningMessageWasmModule implements WasmModule {
  external Object /* Promise */ call([String? moduleName]);
  external LightningMessageWasmModule bind(dynamic thisArg, String moduleName);
  external dynamic /* void */ wire_verify(NativePortType port_, String message, String signature, String public_key);

  external dynamic /* void */ wire_recover_node_id(NativePortType port_, String message, String signature);

  external dynamic /* void */ wire_from_seed__static_method__Signer(NativePortType port_, Uint8List seed);

  external dynamic /* void */ wire_from_ldk_seed__static_method__Signer(NativePortType port_, Uint8List seed);

  external dynamic /* void */ wire_sign__method__Signer(NativePortType port_, List<dynamic> that, String message);
}

// Section: WASM wire connector

class LightningMessageWire extends FlutterRustBridgeWasmWireBase<LightningMessageWasmModule> {
  LightningMessageWire(FutureOr<WasmModule> module) : super(WasmModule.cast<LightningMessageWasmModule>(module));

  void wire_verify(NativePortType port_, String message, String signature, String public_key) => wasmModule.wire_verify(port_, message, signature, public_key);

  void wire_recover_node_id(NativePortType port_, String message, String signature) => wasmModule.wire_recover_node_id(port_, message, signature);

  void wire_from_seed__static_method__Signer(NativePortType port_, Uint8List seed) => wasmModule.wire_from_seed__static_method__Signer(port_, seed);

  void wire_from_ldk_seed__static_method__Signer(NativePortType port_, Uint8List seed) => wasmModule.wire_from_ldk_seed__static_method__Signer(port_, seed);

  void wire_sign__method__Signer(NativePortType port_, List<dynamic> that, String message) => wasmModule.wire_sign__method__Signer(port_, that, message);
}
